name    'CERNOps-fts'
version '0.0.5'
source 'https://github.com/cernops/puppet-fts'
author 'Steve Traylen'
license 'Apache License, Version 2.0'
summary 'Manages FTS Servers'
description 'Manages FTS Clients'
project_page 'https://github.com/cernops/puppet-fts'

## Add dependencies, if any:
dependency 'puppetlabs/inifile', '>= 0.0.0'
dependency 'CERNOps/fetchcrl', '>= 0.0.0'
dependency 'CERNOps/voms', '>= 0.0.0'
dependency 'erwbgy/limits', '>= 0.0.0'
dependency 'domcleal/augeasproviders', '>= 0.0.0'
